// ********RoostGPT********
/*
Test generated by RoostGPT for test csharp-nunit using AI Type AWS Bedrock Runtime AI and AI Model eu.anthropic.claude-sonnet-4-20250514-v1:0

ROOST_METHOD_HASH=Calculate_bd682b7321
ROOST_METHOD_SIG_HASH=Calculate_54551500b1

   ########## Test - Scenarios ##########  

Scenario 1: Valid Discount Rate and Cash Flows Calculation

Details:
  TestName: CalculateNetPresentValue_WithValidDiscountRateAndCashFlows_ReturnsCorrectValue
  Description: This test verifies that the Calculate method correctly computes the net present value when provided with a valid positive discount rate and a list of cash flows. It ensures the mathematical calculation follows the NPV formula and returns a properly rounded result.
Execution:
  Arrange: Set up a discount rate of 0.1 (10%) and a list of cash flows containing values [100, 200, 300].
  Act: Call the Calculate method with the prepared discount rate and cash flows list.
  Assert: Use NUnit's Assert.AreEqual to verify that the returned value matches the expected NPV calculation result rounded to 2 decimal places.
Validation:
  The assertion verifies that the NPV calculation is mathematically correct using the formula: sum of (cash flow / (1 + discount rate)^period).
  This test is significant as it validates the core functionality of the financial calculation method, ensuring accurate present value computations for investment analysis.

Scenario 2: Zero Discount Rate Calculation

Details:
  TestName: CalculateNetPresentValue_WithZeroDiscountRate_ReturnsSumOfCashFlows
  Description: This test checks the behavior when the discount rate is zero, which should result in the net present value being equal to the simple sum of all cash flows since no discounting occurs.
Execution:
  Arrange: Set the discount rate to 0.0 and create a list of cash flows with values [50, 100, 150].
  Act: Invoke the Calculate method with the zero discount rate and cash flows.
  Assert: Use Assert.AreEqual to confirm the result equals the sum of cash flows (300.00).
Validation:
  This assertion ensures that when no discounting is applied (rate = 0), the method correctly returns the undiscounted total.
  The test is important for edge case handling and validates that the mathematical formula works correctly at the boundary condition.

Scenario 3: Single Cash Flow Calculation

Details:
  TestName: CalculateNetPresentValue_WithSingleCashFlow_ReturnsCorrectPresentValue
  Description: This test validates the calculation when only one cash flow is provided, ensuring the method handles minimal input correctly and applies the discount to the single value.
Execution:
  Arrange: Set up a discount rate of 0.05 (5%) and a cash flows list containing a single value [1000].
  Act: Call the Calculate method with the single cash flow scenario.
  Assert: Use Assert.AreEqual to verify the result equals 1000.00 (since the first cash flow at period 0 is not discounted).
Validation:
  The assertion confirms that single cash flows are processed correctly without discounting for period 0.
  This test ensures the method works with minimal valid input and handles the edge case of a single cash flow appropriately.

Scenario 4: Negative Discount Rate Exception

Details:
  TestName: CalculateNetPresentValue_WithNegativeDiscountRate_ThrowsArgumentException
  Description: This test verifies that the method properly validates input parameters and throws an ArgumentException when a negative discount rate is provided, preventing invalid financial calculations.
Execution:
  Arrange: Set up a negative discount rate of -0.1 and a valid cash flows list [100, 200].
  Act: Attempt to call the Calculate method with the negative discount rate.
  Assert: Use Assert.Throws<ArgumentException> to verify that the expected exception is thrown with the correct error message.
Validation:
  The assertion ensures proper input validation and error handling for invalid discount rates.
  This test is crucial for maintaining data integrity and preventing nonsensical financial calculations that could mislead users.

Scenario 5: Empty Cash Flows List Exception

Details:
  TestName: CalculateNetPresentValue_WithEmptyCashFlowsList_ThrowsArgumentException
  Description: This test checks that the method validates the cash flows parameter and throws an appropriate exception when an empty list is provided, as NPV calculation requires at least one cash flow.
Execution:
  Arrange: Set up a valid discount rate of 0.08 and an empty cash flows list.
  Act: Call the Calculate method with the empty cash flows list.
  Assert: Use Assert.Throws<ArgumentException> to confirm the method throws the expected exception with the appropriate error message.
Validation:
  The assertion validates that the method enforces business rules requiring non-empty cash flow data.
  This test is essential for preventing runtime errors and ensuring meaningful financial calculations.

Scenario 6: Large Cash Flow Values Calculation

Details:
  TestName: CalculateNetPresentValue_WithLargeCashFlowValues_HandlesCalculationCorrectly
  Description: This test ensures the method can handle large numerical values without overflow or precision issues, testing the robustness of the calculation with realistic large-scale financial data.
Execution:
  Arrange: Set up a discount rate of 0.12 and cash flows containing large values [1000000, 2000000, 3000000].
  Act: Execute the Calculate method with the large cash flow values.
  Assert: Use Assert.AreEqual to verify the calculated NPV is within expected ranges and properly rounded.
Validation:
  The assertion confirms that large financial values are processed accurately without numerical instability.
  This test is important for real-world applications where cash flows can involve substantial amounts.

Scenario 7: High Discount Rate Calculation

Details:
  TestName: CalculateNetPresentValue_WithHighDiscountRate_ReturnsLowPresentValue
  Description: This test validates the mathematical behavior when a high discount rate is applied, ensuring that future cash flows are heavily discounted and the NPV reflects this appropriately.
Execution:
  Arrange: Set up a high discount rate of 0.5 (50%) and cash flows [100, 100, 100, 100].
  Act: Call the Calculate method with the high discount rate scenario.
  Assert: Use Assert.AreEqual to verify that the NPV is significantly lower than the sum of cash flows due to heavy discounting.
Validation:
  The assertion ensures that high discount rates produce mathematically correct results with substantial present value reduction.
  This test validates the method's accuracy across the full range of realistic discount rate values.

Scenario 8: Mixed Positive and Negative Cash Flows

Details:
  TestName: CalculateNetPresentValue_WithMixedPositiveNegativeCashFlows_CalculatesCorrectly
  Description: This test verifies the method's ability to handle realistic scenarios where cash flows include both positive inflows and negative outflows, ensuring proper NPV calculation for complex investment projects.
Execution:
  Arrange: Set up a discount rate of 0.1 and mixed cash flows [-1000, 500, 400, 300] representing initial investment and subsequent returns.
  Act: Execute the Calculate method with the mixed cash flows.
  Assert: Use Assert.AreEqual to verify the NPV calculation accounts for both positive and negative values correctly.
Validation:
  The assertion confirms that the method handles realistic investment scenarios with initial costs and future benefits.
  This test is crucial for validating real-world investment analysis where projects typically involve upfront costs followed by returns.

Scenario 9: Precision and Rounding Validation

Details:
  TestName: CalculateNetPresentValue_WithDecimalCashFlows_RoundsToTwoDecimalPlaces
  Description: This test ensures that the method correctly rounds the final result to two decimal places as specified, maintaining consistent financial reporting standards regardless of intermediate calculation precision.
Execution:
  Arrange: Set up a discount rate of 0.07 and cash flows that will produce a result requiring rounding [33.333, 66.666, 99.999].
  Act: Call the Calculate method with values that test rounding behavior.
  Assert: Use Assert.AreEqual to verify the result is properly rounded to exactly two decimal places.
Validation:
  The assertion ensures consistent financial reporting format with proper decimal precision.
  This test is important for maintaining professional financial calculation standards and preventing precision-related inconsistencies.

Scenario 10: Very Small Discount Rate Calculation

Details:
  TestName: CalculateNetPresentValue_WithVerySmallDiscountRate_CalculatesAccurately
  Description: This test validates the method's precision when dealing with very small discount rates, ensuring that minimal discounting scenarios are handled accurately without precision loss.
Execution:
  Arrange: Set up a very small discount rate of 0.001 (0.1%) and cash flows [1000, 1000, 1000].
  Act: Execute the Calculate method with the minimal discount rate.
  Assert: Use Assert.AreEqual to verify that the NPV is calculated correctly with minimal discounting applied.
Validation:
  The assertion ensures accuracy in low-risk, low-discount scenarios common in stable financial environments.
  This test validates the method's precision across the full spectrum of realistic discount rate values.


================================VULNERABILITIES================================
Vulnerability: CWE-369: Divide by Zero
Issue: The Math.Pow function can return 0 when (1 + discountRate) equals 0, causing division by zero in the present value calculation. This occurs when discountRate equals -1, which passes the negative validation but creates arithmetic exception.
Solution: Add validation to prevent discountRate from being -1 or any value that makes (1 + discountRate) <= 0: if (discountRate <= -1) { throw new ArgumentException("Discount rate must be greater than -1"); }

Vulnerability: CWE-20: Improper Input Validation
Issue: The cashFlows parameter accepts null values without validation, leading to NullReferenceException when accessing Count property or enumerating the collection.
Solution: Add null validation at method start: if (cashFlows == null) { throw new ArgumentNullException(nameof(cashFlows)); }

Vulnerability: CWE-681: Incorrect Conversion between Numeric Types
Issue: Math.Pow returns double but can produce infinity or NaN values for extreme inputs, which propagate through calculations without detection, potentially causing silent failures in financial calculations.
Solution: Validate Math.Pow results and check for special values: var denominator = Math.Pow(1 + discountRate, i); if (double.IsInfinity(denominator) || double.IsNaN(denominator)) { throw new OverflowException("Calculation overflow detected"); }

Vulnerability: CWE-190: Integer Overflow
Issue: Large collection indexes in LINQ Select can cause integer overflow when passed to Math.Pow, especially with high discount rates and many cash flows, leading to incorrect calculations.
Solution: Add bounds checking for collection size and validate intermediate calculations: if (cashFlows.Count > 1000) { throw new ArgumentException("Too many cash flows for safe calculation"); }

================================================================================

*/

// ********RoostGPT********
using System;
using System.Collections.Generic;
using NUnit.Framework;
using Algorithms.Financial;
using static System.Math;

namespace Algorithms.Financial.Test
{
    [TestFixture]
    public class CalculateTest
    {
        private double _tolerance;

        [SetUp]
        public void SetUp()
        {
            _tolerance = 0.01; // TODO: Adjust tolerance if needed for precision testing
        }

        [Test]
        public void CalculateNetPresentValue_WithValidDiscountRateAndCashFlows_ReturnsCorrectValue()
        {
            // Arrange
            double discountRate = 0.1;
            List<double> cashFlows = new List<double> { 100, 200, 300 };
            double expected = Round(100 / Pow(1.1, 0) + 200 / Pow(1.1, 1) + 300 / Pow(1.1, 2), 2);

            // Act
            double actual = PresentValue.Calculate(discountRate, cashFlows);

            // Assert
            Assert.That(actual, Is.EqualTo(expected));
        }

        [Test]
        public void CalculateNetPresentValue_WithZeroDiscountRate_ReturnsSumOfCashFlows()
        {
            // Arrange
            double discountRate = 0.0;
            List<double> cashFlows = new List<double> { 50, 100, 150 };
            double expected = 300.00;

            // Act
            double actual = PresentValue.Calculate(discountRate, cashFlows);

            // Assert
            Assert.That(actual, Is.EqualTo(expected));
        }

        [Test]
        public void CalculateNetPresentValue_WithSingleCashFlow_ReturnsCorrectPresentValue()
        {
            // Arrange
            double discountRate = 0.05;
            List<double> cashFlows = new List<double> { 1000 };
            double expected = 1000.00;

            // Act
            double actual = PresentValue.Calculate(discountRate, cashFlows);

            // Assert
            Assert.That(actual, Is.EqualTo(expected));
        }

        [Test]
        public void CalculateNetPresentValue_WithNegativeDiscountRate_ThrowsArgumentException()
        {
            // Arrange
            double discountRate = -0.1;
            List<double> cashFlows = new List<double> { 100, 200 };

            // Act & Assert
            ArgumentException exception = Assert.Throws<ArgumentException>(() => 
                PresentValue.Calculate(discountRate, cashFlows));
            Assert.That(exception.Message, Is.EqualTo("Discount rate cannot be negative"));
        }

        [Test]
        public void CalculateNetPresentValue_WithEmptyCashFlowsList_ThrowsArgumentException()
        {
            // Arrange
            double discountRate = 0.08;
            List<double> cashFlows = new List<double>();

            // Act & Assert
            ArgumentException exception = Assert.Throws<ArgumentException>(() => 
                PresentValue.Calculate(discountRate, cashFlows));
            Assert.That(exception.Message, Is.EqualTo("Cash flows list cannot be empty"));
        }

        [Test]
        public void CalculateNetPresentValue_WithLargeCashFlowValues_HandlesCalculationCorrectly()
        {
            // Arrange
            double discountRate = 0.12;
            List<double> cashFlows = new List<double> { 1000000, 2000000, 3000000 };
            double expected = Round(1000000 / Pow(1.12, 0) + 2000000 / Pow(1.12, 1) + 3000000 / Pow(1.12, 2), 2);

            // Act
            double actual = PresentValue.Calculate(discountRate, cashFlows);

            // Assert
            Assert.That(actual, Is.EqualTo(expected));
        }

        [Test]
        public void CalculateNetPresentValue_WithHighDiscountRate_ReturnsLowPresentValue()
        {
            // Arrange
            double discountRate = 0.5;
            List<double> cashFlows = new List<double> { 100, 100, 100, 100 };
            double expected = Round(100 / Pow(1.5, 0) + 100 / Pow(1.5, 1) + 100 / Pow(1.5, 2) + 100 / Pow(1.5, 3), 2);
            double sumOfCashFlows = 400;

            // Act
            double actual = PresentValue.Calculate(discountRate, cashFlows);

            // Assert
            Assert.That(actual, Is.EqualTo(expected));
            Assert.That(actual, Is.LessThan(sumOfCashFlows));
        }

        [Test]
        public void CalculateNetPresentValue_WithMixedPositiveNegativeCashFlows_CalculatesCorrectly()
        {
            // Arrange
            double discountRate = 0.1;
            List<double> cashFlows = new List<double> { -1000, 500, 400, 300 };
            double expected = Round(-1000 / Pow(1.1, 0) + 500 / Pow(1.1, 1) + 400 / Pow(1.1, 2) + 300 / Pow(1.1, 3), 2);

            // Act
            double actual = PresentValue.Calculate(discountRate, cashFlows);

            // Assert
            Assert.That(actual, Is.EqualTo(expected));
        }

        [Test]
        public void CalculateNetPresentValue_WithDecimalCashFlows_RoundsToTwoDecimalPlaces()
        {
            // Arrange
            double discountRate = 0.07;
            List<double> cashFlows = new List<double> { 33.333, 66.666, 99.999 };
            double expected = Round(33.333 / Pow(1.07, 0) + 66.666 / Pow(1.07, 1) + 99.999 / Pow(1.07, 2), 2);

            // Act
            double actual = PresentValue.Calculate(discountRate, cashFlows);

            // Assert
            Assert.That(actual, Is.EqualTo(expected));
            // Verify result has exactly 2 decimal places
            string actualString = actual.ToString("F2");
            Assert.That(actualString.Split('.')[1].Length, Is.EqualTo(2));
        }

        [Test]
        public void CalculateNetPresentValue_WithVerySmallDiscountRate_CalculatesAccurately()
        {
            // Arrange
            double discountRate = 0.001;
            List<double> cashFlows = new List<double> { 1000, 1000, 1000 };
            double expected = Round(1000 / Pow(1.001, 0) + 1000 / Pow(1.001, 1) + 1000 / Pow(1.001, 2), 2);
            double sumOfCashFlows = 3000;

            // Act
            double actual = PresentValue.Calculate(discountRate, cashFlows);

            // Assert
            Assert.That(actual, Is.EqualTo(expected));
            Assert.That(actual, Is.LessThan(sumOfCashFlows));
            Assert.That(actual, Is.GreaterThan(sumOfCashFlows - 10)); // Should be very close to sum due to minimal discounting
        }
    }
}
