// ********RoostGPT********
/*
Test generated by RoostGPT for test csharp-nunit using AI Type AWS Bedrock Runtime AI and AI Model eu.anthropic.claude-sonnet-4-20250514-v1:0

ROOST_METHOD_HASH=RemovePadding_b2de632775
ROOST_METHOD_SIG_HASH=RemovePadding_f35c694e52

   ########## Test - Scenarios ##########  

Scenario 1: Remove padding from valid input with single byte padding

Details:
  TestName: RemovePadding_ValidInputWithSingleBytePadding_ReturnsDataWithoutPadding
  Description: This test verifies that the RemovePadding method correctly removes a single byte of padding from input data. The test checks the basic functionality where the last byte indicates a padding length of 1, and the method should return the original data without the padding byte.
Execution:
  Arrange: Create a byte array with some data followed by a single padding byte (value 1).
  Act: Call the RemovePadding method with the prepared input data.
  Assert: Use NUnit assertions to verify that the returned array has the correct length (original length minus 1) and contains the expected data without the padding byte.
Validation:
  The assertion verifies that the method correctly interprets the padding length from the last byte and removes exactly that number of bytes from the end of the input.
  This test is significant as it validates the core functionality of the padding removal algorithm in the most basic scenario.

Scenario 2: Remove padding from valid input with multiple byte padding

Details:
  TestName: RemovePadding_ValidInputWithMultipleBytePadding_ReturnsDataWithoutPadding
  Description: This test ensures that the RemovePadding method can handle cases where multiple bytes need to be removed as padding. The test uses input data where the last byte indicates a padding length greater than 1.
Execution:
  Arrange: Create a byte array with data followed by multiple padding bytes, where the last byte contains the padding length value.
  Act: Invoke the RemovePadding method with the multi-byte padded input.
  Assert: Assert that the returned array has the correct reduced length and contains only the original data without any padding bytes.
Validation:
  This assertion confirms that the method can correctly handle padding lengths greater than 1, which is essential for cryptographic padding schemes.
  The test validates the method's ability to process standard padding scenarios used in block cipher operations.

Scenario 3: Handle empty input array

Details:
  TestName: RemovePadding_EmptyInputArray_ReturnsEmptyArray
  Description: This test verifies the method's behavior when provided with an empty byte array as input. The method should handle this edge case gracefully without throwing exceptions.
Execution:
  Arrange: Create an empty byte array as input.
  Act: Call the RemovePadding method with the empty array.
  Assert: Assert that the method returns an empty byte array and does not throw any exceptions.
Validation:
  The assertion ensures that the method implements proper boundary condition handling for empty inputs.
  This test is crucial for preventing runtime errors when the method receives unexpected empty data in real-world scenarios.

Scenario 4: Handle invalid padding length - zero padding

Details:
  TestName: RemovePadding_ZeroPaddingLength_ThrowsArgumentException
  Description: This test checks that the method properly validates padding length and throws an appropriate exception when the last byte indicates zero padding length, which is invalid according to standard padding schemes.
Execution:
  Arrange: Create a byte array where the last byte has a value of 0, indicating invalid zero-length padding.
  Act: Attempt to call the RemovePadding method with the invalid input.
  Assert: Assert that an ArgumentException is thrown with an appropriate error message about invalid padding length.
Validation:
  This assertion verifies that the method enforces padding validation rules and prevents processing of malformed data.
  The test is important for maintaining data integrity and preventing potential security vulnerabilities from invalid padding.

Scenario 5: Handle invalid padding length - padding length exceeds data length

Details:
  TestName: RemovePadding_PaddingLengthExceedsDataLength_ThrowsArgumentException
  Description: This test ensures that the method detects and rejects cases where the indicated padding length is greater than the total length of the input data, which would be impossible and indicates corrupted or malicious data.
Execution:
  Arrange: Create a small byte array where the last byte value is greater than the array's total length.
  Act: Call the RemovePadding method with this invalid input configuration.
  Assert: Assert that an ArgumentException is thrown indicating invalid padding length.
Validation:
  The assertion confirms that the method includes proper bounds checking to prevent array index violations and data corruption.
  This validation is critical for security and stability, as it prevents the method from attempting impossible operations.

Scenario 6: Handle padding length equal to total data length

Details:
  TestName: RemovePadding_PaddingLengthEqualsDataLength_ReturnsEmptyArray
  Description: This test verifies the method's behavior when the padding length equals the total length of input data, meaning the entire input consists of padding bytes and should result in an empty output.
Execution:
  Arrange: Create a byte array where the last byte value equals the total array length, indicating that all bytes are padding.
  Act: Invoke the RemovePadding method with this all-padding input.
  Assert: Assert that the method returns an empty byte array without throwing exceptions.
Validation:
  This assertion ensures that the method correctly handles the edge case where valid input consists entirely of padding.
  The test validates proper handling of legitimate but unusual padding scenarios that might occur in cryptographic operations.

Scenario 7: Handle single byte input with valid padding

Details:
  TestName: RemovePadding_SingleByteInputWithValidPadding_ReturnsEmptyArray
  Description: This test checks the method's handling of minimal input consisting of a single byte that represents both the data and the padding length indicator.
Execution:
  Arrange: Create a single-element byte array where the byte value is 1, indicating one byte of padding.
  Act: Call the RemovePadding method with the single-byte input.
  Assert: Assert that the method returns an empty array, correctly interpreting the single byte as padding information.
Validation:
  The assertion verifies that the method can process minimal valid input correctly without boundary errors.
  This test ensures robustness when handling the smallest possible valid padded data scenario.

Scenario 8: Verify data integrity after padding removal

Details:
  TestName: RemovePadding_ComplexDataWithPadding_PreservesOriginalDataIntegrity
  Description: This test ensures that the RemovePadding method preserves the integrity of the original data when removing padding, verifying that no data corruption occurs during the removal process.
Execution:
  Arrange: Create a byte array with a known pattern of data followed by valid padding bytes, storing the expected result separately.
  Act: Process the padded data through the RemovePadding method.
  Assert: Assert that the returned data exactly matches the expected original data pattern, byte by byte.
Validation:
  This assertion confirms that the Array.Copy operation and length calculations preserve data integrity completely.
  The test is essential for ensuring that the padding removal process doesn't introduce any data corruption in cryptographic operations.

Scenario 9: Handle maximum valid padding length

Details:
  TestName: RemovePadding_MaximumValidPaddingLength_ProcessesCorrectly
  Description: This test verifies that the method can handle cases where the padding length is at its maximum valid value, which equals the total input length minus one (leaving at least one byte of actual data).
Execution:
  Arrange: Create a byte array where the padding length is equal to the array length minus one, representing the maximum possible valid padding.
  Act: Execute the RemovePadding method with this maximum padding scenario.
  Assert: Assert that the method returns a single-byte array containing the first byte of the original input.
Validation:
  The assertion ensures that the method correctly handles boundary conditions at the upper limit of valid padding lengths.
  This test validates the method's robustness in extreme but valid usage scenarios.

Scenario 10: Handle large input data with small padding

Details:
  TestName: RemovePadding_LargeInputDataWithSmallPadding_ProcessesEfficiently
  Description: This test evaluates the method's performance and correctness when processing large amounts of data with minimal padding, ensuring that the Array.Copy operation works correctly with large data sets.
Execution:
  Arrange: Create a large byte array (several kilobytes) with meaningful data and a small amount of padding at the end.
  Act: Apply the RemovePadding method to the large input dataset.
  Assert: Assert that the output length is correct and that the data integrity is maintained throughout the large array processing.
Validation:
  This assertion verifies that the method scales appropriately with larger data sizes without performance degradation or errors.
  The test ensures that the method remains reliable in real-world scenarios involving substantial amounts of encrypted data.



*/

// ********RoostGPT********
using System;
using NUnit.Framework;
using Algorithms.Crypto.Paddings;

namespace Algorithms.Crypto.Paddings.Test
{
    [TestFixture]
    public class RemovePaddingTest
    {
        private Iso10126D2Padding _padding;

        [SetUp]
        public void SetUp()
        {
            _padding = new Iso10126D2Padding();
        }

        [Test]
        public void RemovePadding_ValidPaddingLength_ReturnsUnpaddedData()
        {
            // Arrange
            byte[] originalData = { 0x10, 0x20, 0x30, 0x40 };
            byte[] paddedData = { 0x10, 0x20, 0x30, 0x40, 0x05, 0x05, 0x05 }; // 3 padding bytes

            // Act
            byte[] result = _padding.RemovePadding(paddedData);

            // Assert
            Assert.That(result.Length, Is.EqualTo(originalData.Length));
            Assert.That(result, Is.EqualTo(originalData));
        }

        [Test]
        public void RemovePadding_SinglePaddingByte_ReturnsUnpaddedData()
        {
            // Arrange
            byte[] originalData = { 0x10, 0x20, 0x30, 0x40, 0x50, 0x60 };
            byte[] paddedData = { 0x10, 0x20, 0x30, 0x40, 0x50, 0x60, 0x01 }; // 1 padding byte

            // Act
            byte[] result = _padding.RemovePadding(paddedData);

            // Assert
            Assert.That(result.Length, Is.EqualTo(originalData.Length));
            Assert.That(result, Is.EqualTo(originalData));
        }

        [Test]
        public void RemovePadding_InvalidPaddingLengthZero_ThrowsArgumentException()
        {
            // Arrange
            byte[] paddedData = { 0x10, 0x20, 0x30, 0x00 }; // Last byte is 0 (invalid)

            // Act & Assert
            var exception = Assert.Throws<ArgumentException>(() => _padding.RemovePadding(paddedData));
            Assert.That(exception.Message, Is.EqualTo("Invalid padding length"));
        }

        [Test]
        public void RemovePadding_PaddingLengthGreaterThanArrayLength_ThrowsArgumentException()
        {
            // Arrange
            byte[] paddedData = { 0x10, 0x20, 0x30, 0x05 }; // Padding length 5 > array length 4

            // Act & Assert
            var exception = Assert.Throws<ArgumentException>(() => _padding.RemovePadding(paddedData));
            Assert.That(exception.Message, Is.EqualTo("Invalid padding length"));
        }

        [Test]
        public void RemovePadding_EmptyArray_ReturnsEmptyArray()
        {
            // Arrange
            byte[] paddedData = new byte[0];

            // Act
            byte[] result = _padding.RemovePadding(paddedData);

            // Assert
            Assert.That(result.Length, Is.EqualTo(0));
            Assert.That(result, Is.EqualTo(Array.Empty<byte>()));
        }

        [Test]
        public void RemovePadding_FullArrayPadding_ReturnsEmptyArray()
        {
            // Arrange
            byte[] paddedData = { 0x03, 0x03, 0x03 }; // All bytes are padding

            // Act
            byte[] result = _padding.RemovePadding(paddedData);

            // Assert
            Assert.That(result.Length, Is.EqualTo(0));
            Assert.That(result, Is.EqualTo(Array.Empty<byte>()));
        }

        [Test]
        public void RemovePadding_LargeArrayWithValidPadding_ReturnsCorrectUnpaddedData()
        {
            // Arrange
            byte[] originalData = new byte[1000];
            for (int i = 0; i < originalData.Length; i++)
            {
                originalData[i] = (byte)(i % 256);
            }
            byte[] paddedData = new byte[1005];
            Array.Copy(originalData, paddedData, originalData.Length);
            for (int i = originalData.Length; i < paddedData.Length; i++)
            {
                paddedData[i] = 0x05; // 5 padding bytes
            }

            // Act
            byte[] result = _padding.RemovePadding(paddedData);

            // Assert
            Assert.That(result.Length, Is.EqualTo(originalData.Length));
            Assert.That(result, Is.EqualTo(originalData));
        }

        [Test]
        public void RemovePadding_MaxPaddingLength_ReturnsCorrectData()
        {
            // Arrange
            byte[] originalData = { 0x10 };
            byte[] paddedData = new byte[256];
            paddedData[0] = 0x10;
            for (int i = 1; i < paddedData.Length; i++)
            {
                paddedData[i] = 0xFF; // 255 padding bytes
            }

            // Act
            byte[] result = _padding.RemovePadding(paddedData);

            // Assert
            Assert.That(result.Length, Is.EqualTo(originalData.Length));
            Assert.That(result, Is.EqualTo(originalData));
        }

        [Test]
        public void RemovePadding_NullInput_ThrowsNullReferenceException()
        {
            // Arrange
            byte[] paddedData = null;

            // Act & Assert
            Assert.Throws<NullReferenceException>(() => _padding.RemovePadding(paddedData));
        }

        [Test]
        public void RemovePadding_DataIntegrityPreservation_MaintainsOriginalBytes()
        {
            // Arrange
            byte[] originalData = { 0x00, 0xFF, 0x7F, 0x80, 0x01, 0xFE };
            byte[] paddedData = { 0x00, 0xFF, 0x7F, 0x80, 0x01, 0xFE, 0x02, 0x02 }; // 2 padding bytes

            // Act
            byte[] result = _padding.RemovePadding(paddedData);

            // Assert
            Assert.That(result.Length, Is.EqualTo(originalData.Length));
            for (int i = 0; i < originalData.Length; i++)
            {
                Assert.That(result[i], Is.EqualTo(originalData[i]));
            }
        }

        [Test]
        public void RemovePadding_SingleByteArray_ValidPadding_ReturnsEmptyArray()
        {
            // Arrange
            byte[] paddedData = { 0x01 }; // Single byte indicating 1 padding byte

            // Act
            byte[] result = _padding.RemovePadding(paddedData);

            // Assert
            Assert.That(result.Length, Is.EqualTo(0));
            Assert.That(result, Is.EqualTo(Array.Empty<byte>()));
        }
    }
}
