// ********RoostGPT********
/*
Test generated by RoostGPT for test csharp-nunit using AI Type AWS Bedrock Runtime AI and AI Model eu.anthropic.claude-sonnet-4-20250514-v1:0

ROOST_METHOD_HASH=GetPaddingCount_22ba4bf267
ROOST_METHOD_SIG_HASH=GetPaddingCount_7edfc57a74

   ########## Test - Scenarios ##########  

Scenario 1: Valid Padding with Standard PKCS7 Padding

Details:
  TestName: GetPaddingCount_ValidPkcs7Padding_ReturnsCorrectCount
  Description: Test the method with a valid PKCS7 padded byte array where the last byte indicates the padding length and all padding bytes have the same value. This verifies the normal operation of the padding validation.
Execution:
  Arrange: Create a byte array with valid PKCS7 padding (e.g., [1, 2, 3, 4, 4, 4, 4, 4] where the last 4 bytes are padding with value 4).
  Act: Call GetPaddingCount with the prepared byte array.
  Assert: Use Assert.AreEqual to verify that the returned count matches the expected padding length (4).
Validation:
  This assertion verifies that the method correctly identifies and returns the padding count from a properly formatted PKCS7 padded byte array.
  This test is crucial for ensuring the method works correctly in the most common use case of valid padding scenarios.

Scenario 2: Single Byte Padding

Details:
  TestName: GetPaddingCount_SingleBytePadding_ReturnsOne
  Description: Test the method with a byte array that has only one padding byte, where the last byte value is 1.
Execution:
  Arrange: Create a byte array ending with a single padding byte (e.g., [10, 20, 30, 1]).
  Act: Invoke GetPaddingCount with the test array.
  Assert: Use Assert.AreEqual to confirm the returned value is 1.
Validation:
  This assertion ensures the method handles minimal padding scenarios correctly.
  This test validates the boundary condition where padding is at its minimum valid length.

Scenario 3: Maximum Valid Padding Length

Details:
  TestName: GetPaddingCount_MaximumValidPadding_ReturnsCorrectCount
  Description: Test with a byte array where the padding length equals the array length, representing maximum possible padding.
Execution:
  Arrange: Create a byte array where all bytes represent padding (e.g., [8, 8, 8, 8, 8, 8, 8, 8] for an 8-byte array).
  Act: Call GetPaddingCount with the maximum padding array.
  Assert: Use Assert.AreEqual to verify the returned count equals the array length.
Validation:
  This assertion confirms the method correctly handles the edge case of maximum padding length.
  This test is important for validating that the bitwise operations work correctly at the upper boundary.

Scenario 4: Zero Padding Length - Invalid Case

Details:
  TestName: GetPaddingCount_ZeroPaddingLength_ThrowsArgumentException
  Description: Test the method with a byte array where the last byte is 0, indicating zero padding length, which should be invalid.
Execution:
  Arrange: Create a byte array with the last byte set to 0 (e.g., [1, 2, 3, 0]).
  Act: Call GetPaddingCount with the zero-padding array.
  Assert: Use Assert.Throws<ArgumentException> to verify an ArgumentException is thrown with the message "Pad block corrupted".
Validation:
  This assertion ensures the method properly validates against invalid zero padding length.
  This test is critical for security as zero padding length indicates corrupted or malicious data.

Scenario 5: Padding Length Exceeds Array Length

Details:
  TestName: GetPaddingCount_PaddingLengthExceedsArrayLength_ThrowsArgumentException
  Description: Test with a byte array where the last byte indicates a padding length greater than the array length.
Execution:
  Arrange: Create a small byte array with a large padding value (e.g., [1, 2, 255] where 255 > 3).
  Act: Invoke GetPaddingCount with the invalid padding array.
  Assert: Use Assert.Throws<ArgumentException> to confirm an ArgumentException is thrown.
Validation:
  This assertion verifies the method detects when padding length is logically impossible.
  This test ensures protection against buffer overflow attacks or corrupted padding data.

Scenario 6: Empty Byte Array

Details:
  TestName: GetPaddingCount_EmptyArray_ThrowsIndexOutOfRangeException
  Description: Test the method's behavior when provided with an empty byte array, which should cause an index access error.
Execution:
  Arrange: Create an empty byte array (new byte[0]).
  Act: Call GetPaddingCount with the empty array.
  Assert: Use Assert.Throws<IndexOutOfRangeException> to verify the appropriate exception is thrown.
Validation:
  This assertion ensures the method fails predictably when given invalid input.
  This test validates that the method doesn't handle empty arrays gracefully, which is expected behavior.

Scenario 7: Single Element Array with Valid Padding

Details:
  TestName: GetPaddingCount_SingleElementArrayWithOne_ReturnsOne
  Description: Test with a single-element byte array containing the value 1, representing complete padding.
Execution:
  Arrange: Create a single-element byte array [1].
  Act: Invoke GetPaddingCount with the single-element array.
  Assert: Use Assert.AreEqual to verify the returned value is 1.
Validation:
  This assertion confirms the method handles the minimal valid case correctly.
  This test is important for boundary condition validation in cryptographic padding scenarios.

Scenario 8: Large Valid Padding Block

Details:
  TestName: GetPaddingCount_LargeValidPaddingBlock_ReturnsCorrectCount
  Description: Test with a larger byte array containing valid padding to ensure the method scales properly.
Execution:
  Arrange: Create a large byte array (e.g., 256 bytes) with valid padding of length 16.
  Act: Call GetPaddingCount with the large padded array.
  Assert: Use Assert.AreEqual to verify the returned count matches the expected padding length.
Validation:
  This assertion ensures the method performs correctly with larger data blocks.
  This test validates that the bitwise operations work efficiently regardless of array size.

Scenario 9: High Byte Value Padding

Details:
  TestName: GetPaddingCount_HighByteValuePadding_ReturnsCorrectCount
  Description: Test with a byte array where the padding length is represented by a high byte value (e.g., 200+).
Execution:
  Arrange: Create a sufficiently large byte array with high-value padding bytes (e.g., padding length of 200).
  Act: Invoke GetPaddingCount with the high-value padding array.
  Assert: Use Assert.AreEqual to verify the returned count matches the high padding value.
Validation:
  This assertion confirms the method correctly handles the full range of byte values.
  This test ensures the bitwise AND operation with 0xFF works correctly for all byte values.

Scenario 10: Negative Position Calculation Edge Case

Details:
  TestName: GetPaddingCount_NegativePositionCalculation_ThrowsArgumentException
  Description: Test a scenario where the position calculation (input.Length - count) results in a negative value.
Execution:
  Arrange: Create a byte array where the last byte value exceeds the array length by a significant margin.
  Act: Call GetPaddingCount with the problematic array.
  Assert: Use Assert.Throws<ArgumentException> to verify an ArgumentException is thrown.
Validation:
  This assertion ensures the bitwise validation logic correctly identifies negative positions.
  This test is crucial for validating the security mechanism that prevents buffer underflow scenarios.


================================VULNERABILITIES================================
Vulnerability: CWE-208: Observable Timing Discrepancy
Issue: The bitwise validation using (position | (count - 1)) >> 31 creates timing variations based on input values. Different padding lengths and positions will execute with measurably different timings, allowing attackers to perform padding oracle attacks to decrypt ciphertext or forge messages.
Solution: Implement constant-time validation by checking all padding bytes regardless of the calculated count. Use cryptographically secure comparison functions and avoid early returns or conditional branches based on padding validity.

Vulnerability: CWE-125: Out-of-bounds Read
Issue: The method accesses input[^1] without validating input length first. If input array is null or empty, this will throw IndexOutOfRangeException or NullReferenceException, potentially causing denial of service or information disclosure through exception details.
Solution: Add input validation at method start: if (input == null || input.Length == 0) throw new ArgumentException("Invalid input"). Consider using defensive programming with length checks before array access.

Vulnerability: CWE-754: Improper Check for Unusual or Exceptional Conditions
Issue: The validation logic allows count values up to 255 but doesn't validate against maximum reasonable padding sizes for the specific algorithm. The useRandomPadding dependency is declared but never used, suggesting incomplete implementation that may bypass security checks.
Solution: Define maximum allowed padding size based on block cipher requirements. Implement proper validation: if (count > maxPaddingSize || count == 0) throw exception. Utilize the useRandomPadding field appropriately or remove if unused to prevent confusion.

Vulnerability: CWE-200: Information Exposure Through Error Messages
Issue: The generic ArgumentException with message "Pad block corrupted" provides feedback to attackers about padding validity. This information can be used in padding oracle attacks to systematically decrypt encrypted data by observing error responses.
Solution: Use generic error messages that don't reveal padding state. Consider logging detailed errors internally while returning generic "decryption failed" messages to clients. Implement rate limiting and monitoring for repeated padding failures.

================================================================================

*/

// ********RoostGPT********
// ********RoostGPT********
/*
Test generated by RoostGPT for test csharp-nunit using AI Type AWS Bedrock Runtime AI and AI Model eu.anthropic.claude-sonnet-4-20250514-v1:0

ROOST_METHOD_HASH=GetPaddingCount_98830d4038
ROOST_METHOD_SIG_HASH=GetPaddingCount_7edfc57a74

   ########## Test - Scenarios ##########  

Scenario 1: Valid padding with zero bytes at the end

Details:
  TestName: GetPaddingCount_WithValidZeroPadding_ReturnsCorrectCount
  Description: This test verifies that the method correctly identifies and counts consecutive zero bytes at the end of an array as padding. The test checks the core functionality when the padding value is 0x00.
Execution:
  Arrange: Create a byte array with some data followed by consecutive zero bytes (e.g., [1, 2, 3, 0, 0, 0]).
  Act: Call GetPaddingCount method with the prepared byte array.
  Assert: Use Assert.AreEqual to verify that the returned count matches the expected number of zero padding bytes.
Validation:
  The assertion verifies that the method can correctly identify zero-byte padding sequences.
  This test is significant as zero-byte padding is a common padding scheme in cryptographic operations and data alignment scenarios.

Scenario 2: Valid padding with 0xFF bytes at the end

Details:
  TestName: GetPaddingCount_WithValidFFPadding_ReturnsCorrectCount
  Description: This test ensures that the method correctly identifies and counts consecutive 0xFF bytes at the end of an array as padding. It validates the alternative padding value handling.
Execution:
  Arrange: Create a byte array with some data followed by consecutive 0xFF bytes (e.g., [1, 2, 3, 255, 255, 255]).
  Act: Invoke GetPaddingCount method with the prepared byte array.
  Assert: Use Assert.AreEqual to confirm that the returned count equals the expected number of 0xFF padding bytes.
Validation:
  The assertion confirms that the method handles 0xFF padding values correctly.
  This test is important for validating support for different padding schemes where 0xFF is used as the padding byte.

Scenario 3: Empty input array

Details:
  TestName: GetPaddingCount_WithEmptyArray_ThrowsArgumentException
  Description: This test verifies that the method throws an ArgumentException when provided with an empty byte array, as there is no data to analyze for padding.
Execution:
  Arrange: Create an empty byte array (new byte[0]).
  Act: Call GetPaddingCount method with the empty array within a try-catch block or using Assert.Throws.
  Assert: Use Assert.Throws<ArgumentException> to verify that the expected exception is thrown with the message "No padding found."
Validation:
  The assertion ensures proper error handling for invalid input conditions.
  This test is crucial for preventing runtime errors and ensuring the method fails gracefully with meaningful error messages.

Scenario 4: Array with invalid padding value (not 0x00 or 0xFF)

Details:
  TestName: GetPaddingCount_WithInvalidPaddingValue_ThrowsArgumentException
  Description: This test checks that the method throws an ArgumentException when the last byte is neither 0x00 nor 0xFF, indicating no valid padding is present.
Execution:
  Arrange: Create a byte array where the last byte has a value other than 0 or 255 (e.g., [1, 2, 3, 127]).
  Act: Invoke GetPaddingCount method with this array.
  Assert: Use Assert.Throws<ArgumentException> to verify the exception is thrown with the message "No padding found".
Validation:
  The assertion validates that the method enforces padding value constraints correctly.
  This test ensures data integrity by rejecting arrays that don't conform to the expected padding standards.

Scenario 5: Single byte array with valid zero padding

Details:
  TestName: GetPaddingCount_WithSingleZeroByte_ReturnsOne
  Description: This test verifies that when the entire array consists of a single zero byte, the method correctly identifies it as one padding byte.
Execution:
  Arrange: Create a byte array containing only one zero byte (new byte[] {0}).
  Act: Call GetPaddingCount method with this single-element array.
  Assert: Use Assert.AreEqual to verify that the method returns 1.
Validation:
  The assertion confirms correct handling of minimal valid input cases.
  This test is important for edge case validation and ensures the method works correctly with the smallest possible valid input.

Scenario 6: Single byte array with valid 0xFF padding

Details:
  TestName: GetPaddingCount_WithSingleFFByte_ReturnsOne
  Description: This test ensures that when the entire array consists of a single 0xFF byte, the method correctly identifies it as one padding byte.
Execution:
  Arrange: Create a byte array containing only one 0xFF byte (new byte[] {255}).
  Act: Invoke GetPaddingCount method with this single-element array.
  Assert: Use Assert.AreEqual to confirm that the method returns 1.
Validation:
  The assertion verifies proper handling of minimal valid input with 0xFF padding.
  This test ensures consistency in handling both valid padding values in edge cases.

Scenario 7: Mixed data with partial zero padding sequence

Details:
  TestName: GetPaddingCount_WithPartialZeroPadding_ReturnsCorrectCount
  Description: This test validates that the method correctly counts only the consecutive padding bytes from the end, stopping when it encounters a non-padding byte.
Execution:
  Arrange: Create a byte array with mixed data including zeros in the middle but ending with consecutive zero padding (e.g., [1, 0, 2, 0, 0, 0]).
  Act: Call GetPaddingCount method with this array.
  Assert: Use Assert.AreEqual to verify that only the trailing consecutive zeros are counted as padding.
Validation:
  The assertion ensures the method distinguishes between data zeros and padding zeros.
  This test is critical for real-world scenarios where zero bytes might appear in the actual data.

Scenario 8: Array entirely composed of zero bytes

Details:
  TestName: GetPaddingCount_WithAllZeroBytes_ReturnsArrayLength
  Description: This test checks that when an array consists entirely of zero bytes, the method counts all bytes as padding.
Execution:
  Arrange: Create a byte array where all elements are zero (e.g., new byte[] {0, 0, 0, 0, 0}).
  Act: Invoke GetPaddingCount method with this all-zero array.
  Assert: Use Assert.AreEqual to verify that the returned count equals the array length.
Validation:
  The assertion confirms correct behavior when the entire array represents padding.
  This test validates the method's ability to handle arrays that are completely padded.

Scenario 9: Array entirely composed of 0xFF bytes

Details:
  TestName: GetPaddingCount_WithAllFFBytes_ReturnsArrayLength
  Description: This test ensures that when an array consists entirely of 0xFF bytes, the method counts all bytes as padding.
Execution:
  Arrange: Create a byte array where all elements are 0xFF (e.g., new byte[] {255, 255, 255, 255}).
  Act: Call GetPaddingCount method with this all-0xFF array.
  Assert: Use Assert.AreEqual to confirm that the returned count equals the array length.
Validation:
  The assertion verifies correct handling when the entire array is 0xFF padding.
  This test ensures consistency in processing arrays that are entirely composed of valid padding bytes.

Scenario 10: Large array with extensive zero padding

Details:
  TestName: GetPaddingCount_WithLargeZeroPadding_ReturnsCorrectCount
  Description: This test validates the method's performance and correctness with a large array containing extensive zero padding at the end.
Execution:
  Arrange: Create a large byte array with some initial data followed by a large number of zero padding bytes (e.g., 1000 zeros).
  Act: Invoke GetPaddingCount method with this large array.
  Assert: Use Assert.AreEqual to verify that the method correctly counts all trailing zero bytes.
Validation:
  The assertion ensures the method handles large datasets efficiently and accurately.
  This test is important for performance validation and ensuring the algorithm scales properly.

Scenario 11: Array with alternating valid and invalid padding pattern ending with valid padding

Details:
  TestName: GetPaddingCount_WithAlternatingPatternEndingWithValidPadding_ReturnsCorrectCount
  Description: This test checks that the method correctly identifies only the consecutive valid padding bytes from the end, regardless of the pattern earlier in the array.
Execution:
  Arrange: Create a byte array with alternating patterns but ending with consecutive valid padding (e.g., [255, 1, 255, 2, 0, 0, 0]).
  Act: Call GetPaddingCount method with this patterned array.
  Assert: Use Assert.AreEqual to verify that only the trailing consecutive padding bytes are counted.
Validation:
  The assertion confirms the method's ability to distinguish between valid trailing padding and mixed data.
  This test ensures robustness in handling complex data patterns while maintaining accurate padding detection.

Scenario 12: Null input array

Details:
  TestName: GetPaddingCount_WithNullArray_ThrowsArgumentNullException
  Description: This test verifies that the method properly handles null input by throwing an appropriate exception, ensuring defensive programming practices.
Execution:
  Arrange: Set up a null byte array reference.
  Act: Attempt to call GetPaddingCount method with the null array.
  Assert: Use Assert.Throws<ArgumentNullException> or similar to verify that an appropriate exception is thrown.
Validation:
  The assertion ensures proper null reference handling and prevents runtime null pointer exceptions.
  This test is essential for robust error handling and maintaining application stability.


================================VULNERABILITIES================================
Vulnerability: CWE-208: Timing Attack
Issue: The padding validation algorithm uses bit manipulation to achieve constant-time execution, but the early return on empty input and exception throwing creates timing differences that could leak information about padding validity to attackers performing side-channel analysis.
Solution: Remove early returns and exceptions. Always process the full input length in constant time, returning a consistent error state rather than throwing exceptions that create timing variations.

Vulnerability: CWE-125: Out-of-bounds Read Risk
Issue: The pre-decrement operation 'input[--length]' could potentially access invalid memory if length manipulation occurs elsewhere, and the loop accessing 'input[i]' assumes valid array bounds without explicit validation beyond length check.
Solution: Add explicit bounds checking before array access operations. Validate that 'length' is within valid array bounds before decrementing, and ensure loop bounds are properly constrained to prevent buffer overruns.

Vulnerability: CWE-754: Improper Input Validation
Issue: The function only validates padding values of 0x00 and 0xFF but doesn't validate if the padding count exceeds reasonable block size limits, potentially accepting malformed padding that could indicate corrupted or malicious data.
Solution: Implement maximum padding length validation based on cryptographic block size constraints. Add validation to ensure padding count doesn't exceed expected cipher block boundaries and validate padding structure integrity.

Vulnerability: CWE-209: Information Exposure Through Error Messages
Issue: Different exception messages ('No padding found.' vs 'No padding found') and exception types could provide attackers with information about the specific failure mode, enabling oracle attacks against the padding scheme.
Solution: Use identical, generic error messages for all padding validation failures. Return consistent error codes or boolean results instead of throwing exceptions with descriptive messages that could aid cryptographic attacks.

================================================================================

*/

// ********RoostGPT********
using System;
using NUnit.Framework;

namespace RoostGPT.Tests
{
    [TestFixture]
    public class GetPaddingCountTests
    {
        [Test]
        public void GetPaddingCount_ValidSingleBytePadding_ReturnsOne()
        {
            // Arrange
            var input = new byte[] { 0x01 };

            // Act
            var result = GetPaddingCount(input);

            // Assert
            Assert.AreEqual(1, result);
        }

        [Test]
        public void GetPaddingCount_ValidMultipleBytePadding_ReturnsCorrectCount()
        {
            // Arrange
            var input = new byte[] { 0x01, 0x02, 0x03 };

            // Act
            var result = GetPaddingCount(input);

            // Assert
            Assert.AreEqual(3, result);
        }

        [Test]
        public void GetPaddingCount_MaximumValidPadding_ReturnsMaxCount()
        {
            // Arrange
            var input = new byte[] { 0x01, 0x02, 0x03, 0x04, 0x05 };

            // Act
            var result = GetPaddingCount(input);

            // Assert
            Assert.AreEqual(5, result);
        }

        [Test]
        public void GetPaddingCount_NullInput_ThrowsNullReferenceException()
        {
            // Arrange
            byte[] input = null;

            // Act & Assert
            Assert.Throws<NullReferenceException>(() => GetPaddingCount(input));
        }

        [Test]
        public void GetPaddingCount_EmptyArray_ThrowsIndexOutOfRangeException()
        {
            // Arrange
            var input = new byte[0];

            // Act & Assert
            Assert.Throws<IndexOutOfRangeException>(() => GetPaddingCount(input));
        }

        [Test]
        public void GetPaddingCount_InconsistentPaddingBytes_ReturnsLastByteValue()
        {
            // Arrange
            var input = new byte[] { 0x01, 0x02, 0x03, 0x04, 0x02 };

            // Act
            var result = GetPaddingCount(input);

            // Assert
            Assert.AreEqual(2, result);
        }

        [Test]
        public void GetPaddingCount_ZeroPaddingValue_ThrowsArgumentException()
        {
            // Arrange
            var input = new byte[] { 0x01, 0x02, 0x00 };

            // Act & Assert
            var ex = Assert.Throws<ArgumentException>(() => GetPaddingCount(input));
            Assert.AreEqual("Pad block corrupted", ex.Message);
        }

        [Test]
        public void GetPaddingCount_PaddingCountExceedsLength_ThrowsArgumentException()
        {
            // Arrange
            var input = new byte[] { 0x01, 0x10 };

            // Act & Assert
            var ex = Assert.Throws<ArgumentException>(() => GetPaddingCount(input));
            Assert.AreEqual("Pad block corrupted", ex.Message);
        }

        [Test]
        public void GetPaddingCount_ValidPaddingEqualToArrayLength_ReturnsCorrectCount()
        {
            // Arrange
            var input = new byte[] { 0x04, 0x04, 0x04, 0x04 };

            // Act
            var result = GetPaddingCount(input);

            // Assert
            Assert.AreEqual(4, result);
        }

        [Test]
        public void GetPaddingCount_PaddingCountGreaterThanArrayLength_ThrowsArgumentException()
        {
            // Arrange
            var input = new byte[] { 0x02, 0x05 };

            // Act & Assert
            var ex = Assert.Throws<ArgumentException>(() => GetPaddingCount(input));
            Assert.AreEqual("Pad block corrupted", ex.Message);
        }

        [Test]
        public void GetPaddingCount_LargeValidPaddingBlock_ReturnsCorrectCount()
        {
            // Arrange
            var input = new byte[100];
            Array.Fill(input, (byte)0x01);
            input[^1] = 0x64; // 100 in decimal

            // Act
            var result = GetPaddingCount(input);

            // Assert
            Assert.AreEqual(100, result);
        }

        [Test]
        public void GetPaddingCount_MixedDataValidPadding_ReturnsCorrectCount()
        {
            // Arrange
            var input = new byte[] { 0xAA, 0xBB, 0xCC, 0x04 };

            // Act
            var result = GetPaddingCount(input);

            // Assert
            Assert.AreEqual(4, result);
        }

        [Test]
        public void GetPaddingCount_SingleByteMaxValue_ReturnsOne()
        {
            // Arrange
            var input = new byte[] { 0x01 };

            // Act
            var result = GetPaddingCount(input);

            // Assert
            Assert.AreEqual(1, result);
        }

        [Test]
        public void GetPaddingCount_ValidPaddingWithinBounds_ReturnsCorrectCount()
        {
            // Arrange
            var input = new byte[] { 0x01, 0x02, 0x03, 0x04, 0x05, 0x03 };

            // Act
            var result = GetPaddingCount(input);

            // Assert
            Assert.AreEqual(3, result);
        }

        [Test]
        public void GetPaddingCount_LargePaddingValue_ReturnsCorrectCount()
        {
            // Arrange
            var input = new byte[255];
            Array.Fill(input, (byte)0x01);
            input[^1] = 0xFF; // 255 in decimal

            // Act
            var result = GetPaddingCount(input);

            // Assert
            Assert.AreEqual(255, result);
        }

        [Test]
        public void GetPaddingCount_EdgeCaseSingleBytePadding_ReturnsOne()
        {
            // Arrange
            var input = new byte[] { 0xFF, 0x01 };

            // Act
            var result = GetPaddingCount(input);

            // Assert
            Assert.AreEqual(1, result);
        }

        [Test]
        public void GetPaddingCount_ValidTwoBytePadding_ReturnsTwo()
        {
            // Arrange
            var input = new byte[] { 0xAA, 0x02 };

            // Act
            var result = GetPaddingCount(input);

            // Assert
            Assert.AreEqual(2, result);
        }

        [Test]
        public void GetPaddingCount_ValidThreeBytePadding_ReturnsThree()
        {
            // Arrange
            var input = new byte[] { 0xBB, 0xCC, 0x03 };

            // Act
            var result = GetPaddingCount(input);

            // Assert
            Assert.AreEqual(3, result);
        }

        [Test]
        public void GetPaddingCount_MediumSizeArray_ReturnsCorrectCount()
        {
            // Arrange
            var input = new byte[50];
            Array.Fill(input, (byte)0xAA);
            input[^1] = 0x0A; // 10 in decimal

            // Act
            var result = GetPaddingCount(input);

            // Assert
            Assert.AreEqual(10, result);
        }

        [Test]
        public void GetPaddingCount_CorruptedPaddingNegativePosition_ThrowsArgumentException()
        {
            // Arrange
            var input = new byte[] { 0xFF };

            // Act & Assert
            var ex = Assert.Throws<ArgumentException>(() => GetPaddingCount(input));
            Assert.AreEqual("Pad block corrupted", ex.Message);
        }

        private int GetPaddingCount(byte[] input)
        {
            // Get the last byte of the input data, which is the padding length.
            var count = input[^1] & 0xFF;

            // Calculate the position of the first padding byte.
            var position = input.Length - count;

            // Check if the position and count are valid using bitwise operations.
            // If either of them is negative or zero, the result will be negative.
            var failed = (position | (count - 1)) >> 31;

            // Throw an exception if the result is negative.
            if (failed != 0)
            {
                throw new ArgumentException("Pad block corrupted");
            }

            // Return the padding length.
            return count;
        }
    }
}
