// ********RoostGPT********
/*
Test generated by RoostGPT for test csharp-nunit using AI Type AWS Bedrock Runtime AI and AI Model eu.anthropic.claude-sonnet-4-20250514-v1:0

ROOST_METHOD_HASH=CheckOutputLength_df50c8eba2
ROOST_METHOD_SIG_HASH=CheckOutputLength_909d0ffd20

   ########## Test - Scenarios ##########  

Scenario 1: Valid Parameters With Sufficient Buffer Space

Details:
  TestName: CheckOutputLength_ValidParametersWithSufficientSpace_DoesNotThrowException
  Description: This test verifies that the method executes successfully without throwing an exception when provided with valid parameters where the buffer has sufficient space for the specified offset and length combination.

Execution:
  Arrange: Create a byte array buffer of size 10, set offset to 3, length to 5, and provide a test message string.
  Act: Call CheckOutputLength method with the arranged parameters.
  Assert: Verify that no exception is thrown during method execution.

Validation:
  The assertion aims to verify that the method correctly identifies valid buffer space scenarios and allows normal execution flow. This test is significant as it validates the happy path functionality where buffer operations should proceed without restriction.

Scenario 2: Offset Equals Buffer Length Minus Length Boundary Case

Details:
  TestName: CheckOutputLength_OffsetEqualsBufferLengthMinusLength_DoesNotThrowException
  Description: This test examines the boundary condition where the offset exactly equals the buffer length minus the required length, which should be the maximum allowable offset value.

Execution:
  Arrange: Create a byte array buffer of size 8, set offset to 5, length to 3 (where offset equals buffer.Length - length), and provide a test message.
  Act: Invoke CheckOutputLength with the boundary condition parameters.
  Assert: Confirm that no OutputLengthException is thrown.

Validation:
  This assertion verifies that the method correctly handles the exact boundary case where offset equals buffer.Length - length. This test is crucial for ensuring the boundary logic is implemented correctly and prevents off-by-one errors.

Scenario 3: Offset Exceeds Buffer Capacity By One

Details:
  TestName: CheckOutputLength_OffsetExceedsBufferCapacityByOne_ThrowsOutputLengthException
  Description: This test validates that the method throws an OutputLengthException when the offset exceeds the allowable range by exactly one position.

Execution:
  Arrange: Create a byte array buffer of size 6, set offset to 4, length to 3 (making offset > buffer.Length - length by 1), and provide an error message string.
  Act: Call CheckOutputLength method with parameters that exceed buffer capacity.
  Assert: Verify that an OutputLengthException is thrown with the correct message.

Validation:
  The assertion ensures that the method properly detects buffer overflow conditions and throws the appropriate exception. This test is essential for preventing buffer overflow vulnerabilities and maintaining data integrity.

Scenario 4: Large Offset Value Significantly Exceeding Buffer Capacity

Details:
  TestName: CheckOutputLength_LargeOffsetExceedingCapacity_ThrowsOutputLengthException
  Description: This test checks the method's behavior when provided with an offset value that significantly exceeds the buffer's capacity, ensuring robust error handling for extreme cases.

Execution:
  Arrange: Create a byte array buffer of size 5, set offset to 100, length to 2, and provide an appropriate error message.
  Act: Execute CheckOutputLength with the extremely large offset value.
  Assert: Confirm that an OutputLengthException is thrown with the specified message.

Validation:
  This assertion validates that the method handles extreme input values gracefully and consistently throws exceptions for invalid buffer access attempts. The test is important for ensuring system stability under unusual input conditions.

Scenario 5: Zero Length With Valid Offset

Details:
  TestName: CheckOutputLength_ZeroLengthWithValidOffset_DoesNotThrowException
  Description: This test examines the method's behavior when the length parameter is zero but the offset is within valid bounds.

Execution:
  Arrange: Create a byte array buffer of size 7, set offset to 4, length to 0, and provide a test message.
  Act: Call CheckOutputLength with zero length parameter.
  Assert: Verify that no exception is thrown.

Validation:
  The assertion confirms that the method correctly handles zero-length operations, which are valid scenarios in buffer manipulation. This test ensures that edge cases with zero length don't cause unexpected behavior.

Scenario 6: Zero Offset With Large Length

Details:
  TestName: CheckOutputLength_ZeroOffsetWithLargeLength_ThrowsOutputLengthException
  Description: This test validates the method's response when offset is zero but the required length exceeds the buffer size.

Execution:
  Arrange: Create a byte array buffer of size 4, set offset to 0, length to 6, and provide an error message.
  Act: Invoke CheckOutputLength with zero offset but excessive length.
  Assert: Confirm that an OutputLengthException is thrown.

Validation:
  This assertion ensures that the method properly validates the length parameter against buffer capacity regardless of offset value. The test is significant for preventing buffer overruns in scenarios where large data writes are attempted.

Scenario 7: Empty Buffer With Non-Zero Parameters

Details:
  TestName: CheckOutputLength_EmptyBufferWithNonZeroParameters_ThrowsOutputLengthException
  Description: This test checks the method's behavior when an empty buffer is provided with non-zero offset and length parameters.

Execution:
  Arrange: Create an empty byte array buffer (size 0), set offset to 1, length to 1, and provide an error message.
  Act: Call CheckOutputLength with empty buffer and non-zero parameters.
  Assert: Verify that an OutputLengthException is thrown.

Validation:
  The assertion validates that the method correctly identifies impossible operations on empty buffers. This test is crucial for preventing runtime errors when working with uninitialized or empty data structures.

Scenario 8: All Parameters Are Zero

Details:
  TestName: CheckOutputLength_AllParametersZero_DoesNotThrowException
  Description: This test examines the edge case where buffer is empty, offset is zero, and length is zero, which should be a valid scenario.

Execution:
  Arrange: Create an empty byte array buffer (size 0), set offset to 0, length to 0, and provide a test message.
  Act: Execute CheckOutputLength with all zero parameters.
  Assert: Confirm that no exception is thrown.

Validation:
  This assertion ensures that the method handles the minimal valid case correctly where no actual buffer operation is required. The test validates that zero-parameter scenarios don't trigger false positive exceptions.

Scenario 9: Maximum Integer Values For Offset And Length

Details:
  TestName: CheckOutputLength_MaximumIntegerValues_ThrowsOutputLengthException
  Description: This test validates the method's behavior when provided with maximum integer values for offset and length parameters to test arithmetic overflow handling.

Execution:
  Arrange: Create a byte array buffer of size 10, set offset to int.MaxValue, length to int.MaxValue, and provide an error message.
  Act: Call CheckOutputLength with maximum integer values.
  Assert: Verify that an OutputLengthException is thrown.

Validation:
  The assertion ensures that the method handles extreme integer values without causing arithmetic overflow exceptions. This test is important for maintaining system stability under potential malicious input or programming errors.

Scenario 10: Custom Exception Message Validation

Details:
  TestName: CheckOutputLength_InvalidParameters_ThrowsExceptionWithCorrectMessage
  Description: This test specifically validates that the OutputLengthException contains the exact message passed to the method when an exception condition is met.

Execution:
  Arrange: Create a byte array buffer of size 5, set offset to 4, length to 3, and provide a specific custom error message.
  Act: Invoke CheckOutputLength with parameters that will trigger an exception.
  Assert: Verify that the thrown OutputLengthException contains the exact custom message provided.

Validation:
  This assertion confirms that the method properly preserves and passes through custom error messages, enabling meaningful error reporting in applications. The test is essential for ensuring proper error communication to end users or logging systems.


================================VULNERABILITIES================================
Vulnerability: CWE-190: Integer Overflow or Wraparound
Issue: The arithmetic operation 'buffer.Length - length' can cause integer underflow when 'length' is larger than 'buffer.Length', potentially leading to incorrect boundary checks and buffer overflow conditions.
Solution: Add explicit checks to ensure 'length' is not negative and does not exceed 'buffer.Length' before performing arithmetic operations. Use checked arithmetic context or validate inputs: if (length < 0 || length > buffer.Length || offset < 0) throw new ArgumentException();

Vulnerability: CWE-476: NULL Pointer Dereference
Issue: The method does not validate if 'buffer' parameter is null before accessing 'buffer.Length', which could result in NullReferenceException and potential denial of service.
Solution: Add null reference validation at the beginning of the method: if (buffer == null) throw new ArgumentNullException(nameof(buffer));

Vulnerability: CWE-129: Improper Validation of Array Index
Issue: The method only checks if 'offset' exceeds the calculated boundary but does not validate if 'offset' is negative, allowing potential negative array indexing attempts in calling code.
Solution: Include validation for negative offset values: if (offset < 0 || offset > (buffer.Length - length)) throw new OutputLengthException(message);

Vulnerability: CWE-682: Incorrect Calculation
Issue: When 'length' is 0, the boundary check allows 'offset' to equal 'buffer.Length', which may be valid for some scenarios but could indicate off-by-one errors in calling code expecting strict bounds.
Solution: Clarify the intended behavior and document whether offset == buffer.Length is acceptable when length == 0, or adjust the comparison operator based on requirements.

================================================================================

*/

// ********RoostGPT********
using System;
using NUnit.Framework;
using Algorithms.Crypto.Utils;
using Algorithms.Crypto.Exceptions;

namespace Algorithms.Crypto.Utils.Test
{
    [TestFixture]
    public class CheckOutputLength219Test
    {
        private byte[] _buffer;
        private string _testMessage;
        private string _errorMessage;

        [SetUp]
        public void SetUp()
        {
            _testMessage = "Test operation successful";
            _errorMessage = "Buffer capacity exceeded";
        }

        [Test]
        public void CheckOutputLength_ValidParametersWithSufficientSpace_DoesNotThrowException()
        {
            // Arrange
            _buffer = new byte[10];
            int offset = 3;
            int length = 5;

            // Act & Assert
            Assert.DoesNotThrow(() => ValidationUtils.CheckOutputLength(_buffer, offset, length, _testMessage));
        }

        [Test]
        public void CheckOutputLength_OffsetEqualsBufferLengthMinusLength_DoesNotThrowException()
        {
            // Arrange
            _buffer = new byte[8];
            int offset = 5;
            int length = 3;

            // Act & Assert
            Assert.DoesNotThrow(() => ValidationUtils.CheckOutputLength(_buffer, offset, length, _testMessage));
        }

        [Test]
        public void CheckOutputLength_OffsetExceedsBufferCapacityByOne_ThrowsOutputLengthException()
        {
            // Arrange
            _buffer = new byte[6];
            int offset = 4;
            int length = 3;

            // Act & Assert
            var exception = Assert.Throws<OutputLengthException>(() => 
                ValidationUtils.CheckOutputLength(_buffer, offset, length, _errorMessage));
            Assert.That(exception.Message, Is.EqualTo(_errorMessage));
        }

        [Test]
        public void CheckOutputLength_LargeOffsetExceedingCapacity_ThrowsOutputLengthException()
        {
            // Arrange
            _buffer = new byte[5];
            int offset = 100;
            int length = 2;

            // Act & Assert
            var exception = Assert.Throws<OutputLengthException>(() => 
                ValidationUtils.CheckOutputLength(_buffer, offset, length, _errorMessage));
            Assert.That(exception.Message, Is.EqualTo(_errorMessage));
        }

        [Test]
        public void CheckOutputLength_ZeroLengthWithValidOffset_DoesNotThrowException()
        {
            // Arrange
            _buffer = new byte[7];
            int offset = 4;
            int length = 0;

            // Act & Assert
            Assert.DoesNotThrow(() => ValidationUtils.CheckOutputLength(_buffer, offset, length, _testMessage));
        }

        [Test]
        public void CheckOutputLength_ZeroOffsetWithLargeLength_ThrowsOutputLengthException()
        {
            // Arrange
            _buffer = new byte[4];
            int offset = 0;
            int length = 6;

            // Act & Assert
            var exception = Assert.Throws<OutputLengthException>(() => 
                ValidationUtils.CheckOutputLength(_buffer, offset, length, _errorMessage));
            Assert.That(exception.Message, Is.EqualTo(_errorMessage));
        }

        [Test]
        public void CheckOutputLength_EmptyBufferWithNonZeroParameters_ThrowsOutputLengthException()
        {
            // Arrange
            _buffer = new byte[0];
            int offset = 1;
            int length = 1;

            // Act & Assert
            var exception = Assert.Throws<OutputLengthException>(() => 
                ValidationUtils.CheckOutputLength(_buffer, offset, length, _errorMessage));
            Assert.That(exception.Message, Is.EqualTo(_errorMessage));
        }

        [Test]
        public void CheckOutputLength_AllParametersZero_DoesNotThrowException()
        {
            // Arrange
            _buffer = new byte[0];
            int offset = 0;
            int length = 0;

            // Act & Assert
            Assert.DoesNotThrow(() => ValidationUtils.CheckOutputLength(_buffer, offset, length, _testMessage));
        }

        [Test]
        public void CheckOutputLength_MaximumIntegerValues_ThrowsOutputLengthException()
        {
            // Arrange
            _buffer = new byte[10];
            int offset = int.MaxValue;
            int length = int.MaxValue;

            // Act & Assert
            var exception = Assert.Throws<OutputLengthException>(() => 
                ValidationUtils.CheckOutputLength(_buffer, offset, length, _errorMessage));
            Assert.That(exception.Message, Is.EqualTo(_errorMessage));
        }

        [Test]
        public void CheckOutputLength_InvalidParameters_ThrowsExceptionWithCorrectMessage()
        {
            // Arrange
            _buffer = new byte[5];
            int offset = 4;
            int length = 3;
            string customMessage = "Custom error message for validation failure"; // TODO: Change this message as needed

            // Act & Assert
            var exception = Assert.Throws<OutputLengthException>(() => 
                ValidationUtils.CheckOutputLength(_buffer, offset, length, customMessage));
            Assert.That(exception.Message, Is.EqualTo(customMessage));
        }
    }
}
