// ********RoostGPT********
/*
Test generated by RoostGPT for test csharp-nunit using AI Type AWS Bedrock Runtime AI and AI Model eu.anthropic.claude-sonnet-4-20250514-v1:0

ROOST_METHOD_HASH=CheckOutputLength_4514ea8772
ROOST_METHOD_SIG_HASH=CheckOutputLength_d4096d836e

   ########## Test - Scenarios ##########  

Scenario 1: Method throws OutputLengthException when condition is true

Details:
  TestName: CheckOutputLength_WhenConditionIsTrue_ThrowsOutputLengthException
  Description: This test verifies that the CheckOutputLength method throws an OutputLengthException when the condition parameter is true. The test ensures that the exception handling mechanism works correctly for invalid output length conditions.

Execution:
  Arrange: Set up a boolean condition variable with value true and prepare a test message string to be passed to the method.
  Act: Invoke the CheckOutputLength method with condition set to true and the prepared message.
  Assert: Use NUnit's Assert.Throws to verify that an OutputLengthException is thrown with the correct message.

Validation:
  The assertion verifies that the method correctly identifies invalid conditions and throws the appropriate exception type. This test is crucial for ensuring that the cryptographic algorithms properly validate output length constraints and fail fast when invalid conditions are detected, preventing potential security vulnerabilities or incorrect algorithm behavior.

Scenario 2: Method does not throw exception when condition is false

Details:
  TestName: CheckOutputLength_WhenConditionIsFalse_DoesNotThrowException
  Description: This test ensures that the CheckOutputLength method executes without throwing any exception when the condition parameter is false. It validates the normal execution path where output length conditions are satisfied.

Execution:
  Arrange: Set up a boolean condition variable with value false and prepare a test message string.
  Act: Invoke the CheckOutputLength method with condition set to false and the test message.
  Assert: Use NUnit's Assert.DoesNotThrow to verify that no exception is thrown during method execution.

Validation:
  This assertion confirms that the method allows normal program flow to continue when valid conditions are met. This test is essential for verifying that the validation logic doesn't incorrectly block valid operations, ensuring the reliability of cryptographic operations when output length requirements are properly satisfied.

Scenario 3: Method throws OutputLengthException with correct message when condition is true

Details:
  TestName: CheckOutputLength_WhenConditionIsTrue_ThrowsExceptionWithCorrectMessage
  Description: This test validates that when an OutputLengthException is thrown, it contains the exact message that was passed to the method. It ensures proper error message propagation for debugging and error handling purposes.

Execution:
  Arrange: Create a specific test message string with meaningful content that describes the output length validation failure.
  Act: Call the CheckOutputLength method with condition set to true and the specific test message.
  Assert: Use Assert.Throws to catch the OutputLengthException and verify that the exception's message property matches the original input message exactly.

Validation:
  This assertion ensures that error messages are correctly preserved and propagated through the exception mechanism. Proper error messaging is critical in cryptographic applications for troubleshooting, security auditing, and providing meaningful feedback to developers about what specific validation failed.

Scenario 4: Method handles null message parameter when condition is true

Details:
  TestName: CheckOutputLength_WhenConditionIsTrueAndMessageIsNull_ThrowsOutputLengthException
  Description: This test examines the method's behavior when the condition is true but the message parameter is null. It ensures that the method can handle null message values without causing unexpected errors.

Execution:
  Arrange: Set the condition parameter to true and set the message parameter to null.
  Act: Invoke the CheckOutputLength method with the true condition and null message.
  Assert: Verify that an OutputLengthException is thrown, and check that the exception can be properly instantiated even with a null message.

Validation:
  This test ensures robustness in error handling scenarios where the error message might not be properly initialized. It's important for maintaining application stability and preventing secondary errors during exception handling in cryptographic validation routines.

Scenario 5: Method handles empty string message when condition is true

Details:
  TestName: CheckOutputLength_WhenConditionIsTrueAndMessageIsEmpty_ThrowsOutputLengthExceptionWithEmptyMessage
  Description: This test verifies the method's behavior when the condition is true and an empty string is provided as the message parameter. It ensures that empty messages are handled appropriately.

Execution:
  Arrange: Set the condition parameter to true and initialize the message parameter with an empty string.
  Act: Call the CheckOutputLength method with the true condition and empty string message.
  Assert: Use Assert.Throws to verify that an OutputLengthException is thrown and that the exception message is indeed empty.

Validation:
  This assertion validates that the method preserves the exact message content, including empty strings, which might be intentional in certain validation scenarios. This ensures consistency in error handling behavior regardless of message content length.

Scenario 6: Method handles whitespace-only message when condition is true

Details:
  TestName: CheckOutputLength_WhenConditionIsTrueAndMessageIsWhitespace_ThrowsOutputLengthExceptionWithWhitespaceMessage
  Description: This test checks the method's behavior when the condition is true and the message contains only whitespace characters. It ensures that whitespace-only messages are preserved in the exception.

Execution:
  Arrange: Set the condition parameter to true and create a message string containing only whitespace characters (spaces, tabs, newlines).
  Act: Execute the CheckOutputLength method with the true condition and whitespace message.
  Assert: Verify that an OutputLengthException is thrown and that the exception message contains the original whitespace characters.

Validation:
  This test ensures that the method doesn't perform any unexpected string trimming or formatting on the message parameter, maintaining the exact input for accurate error reporting and debugging purposes in cryptographic validation scenarios.

Scenario 7: Method performance with long message string when condition is true

Details:
  TestName: CheckOutputLength_WhenConditionIsTrueAndMessageIsVeryLong_ThrowsOutputLengthExceptionEfficiently
  Description: This test evaluates the method's performance and behavior when handling very long message strings. It ensures that the method can handle large error messages without performance degradation.

Execution:
  Arrange: Create a very long message string (several thousand characters) and set the condition parameter to true.
  Act: Invoke the CheckOutputLength method with the true condition and the long message string.
  Assert: Verify that an OutputLengthException is thrown with the complete long message, and optionally measure execution time to ensure reasonable performance.

Validation:
  This test ensures that the method maintains good performance characteristics even with large error messages, which is important for maintaining overall application responsiveness during error conditions in cryptographic operations.

Scenario 8: Method behavior with special characters in message when condition is true

Details:
  TestName: CheckOutputLength_WhenConditionIsTrueAndMessageContainsSpecialCharacters_PreservesSpecialCharactersInException
  Description: This test verifies that the method correctly handles and preserves special characters, unicode characters, and escape sequences in the message parameter when throwing an exception.

Execution:
  Arrange: Create a message string containing various special characters, unicode symbols, escape sequences, and international characters, then set condition to true.
  Act: Call the CheckOutputLength method with the true condition and the special character message.
  Assert: Verify that the OutputLengthException is thrown and that all special characters are preserved exactly in the exception message.

Validation:
  This assertion ensures that the method maintains full character encoding support and doesn't corrupt or modify special characters during exception creation, which is essential for internationalized applications and proper error message display across different locales and character sets.


================================VULNERABILITIES================================
Vulnerability: CWE-209: Information Exposure Through Error Messages
Issue: The CheckOutputLength method accepts arbitrary string messages that could expose sensitive internal information through exception messages. If callers pass detailed system information or cryptographic details in the message parameter, this could leak sensitive data to attackers who trigger these exceptions.
Solution: Implement message sanitization or use predefined error message templates. Consider logging detailed information separately while exposing only generic error messages to users. Example: Use enum-based error codes mapped to safe, predefined messages.

Vulnerability: CWE-248: Uncaught Exception
Issue: The method throws OutputLengthException without any exception handling context. In cryptographic operations, unhandled exceptions could leave the system in an inconsistent state, potentially exposing partial cryptographic operations or leaving sensitive data in memory.
Solution: Ensure all callers of CheckOutputLength implement proper exception handling. Consider adding documentation specifying the exception contract. Implement secure cleanup mechanisms in calling code to handle cryptographic state properly when exceptions occur.

Vulnerability: CWE-754: Improper Check for Unusual or Exceptional Conditions
Issue: The method only checks a boolean condition without validating the message parameter. Null or malformed messages could cause downstream issues when the exception is constructed or handled, potentially causing application crashes or unexpected behavior in cryptographic workflows.
Solution: Add input validation for the message parameter before creating the exception. Implement null checks and consider message length limits. Example: if (string.IsNullOrEmpty(message)) message = 'Invalid output length detected';

================================================================================

*/

// ********RoostGPT********
using System;
using NUnit.Framework;
using Algorithms.Crypto.Utils;
using Algorithms.Crypto.Exceptions;

namespace Algorithms.Crypto.Utils.Test
{
    [TestFixture]
    public class CheckOutputLengthTest
    {
        private string _testMessage;
        private string _emptyMessage;
        private string _whitespaceMessage;
        private string _longMessage;
        private string _specialCharacterMessage;

        [SetUp]
        public void SetUp()
        {
            _testMessage = "Output length validation failed";
            _emptyMessage = string.Empty;
            _whitespaceMessage = "   \t\n\r   ";
            _longMessage = new string('A', 5000) + " - This is a very long error message for testing performance and memory handling";
            _specialCharacterMessage = "Error: àáâãäåæçèéêë 中文 العربية ñ ü € § ™ ® © ∞ ∑ π Ω ≈ ≠ ≤ ≥ ± ÷ × • ◦ ‰ ‱ ′ ″ ‴";
        }

        [Test]
        public void CheckOutputLength_WhenConditionIsTrue_ThrowsOutputLengthException()
        {
            // Arrange
            bool condition = true;

            // Act & Assert
            Assert.Throws<OutputLengthException>(() => ValidationUtils.CheckOutputLength(condition, _testMessage));
        }

        [Test]
        public void CheckOutputLength_WhenConditionIsFalse_DoesNotThrowException()
        {
            // Arrange
            bool condition = false;

            // Act & Assert
            Assert.DoesNotThrow(() => ValidationUtils.CheckOutputLength(condition, _testMessage));
        }

        [Test]
        public void CheckOutputLength_WhenConditionIsTrue_ThrowsExceptionWithCorrectMessage()
        {
            // Arrange
            bool condition = true;
            string specificMessage = "Specific output length validation error occurred";

            // Act & Assert
            var exception = Assert.Throws<OutputLengthException>(() => ValidationUtils.CheckOutputLength(condition, specificMessage));
            Assert.That(exception.Message, Is.EqualTo(specificMessage));
        }

        [Test]
        public void CheckOutputLength_WhenConditionIsTrueAndMessageIsNull_ThrowsOutputLengthException()
        {
            // Arrange
            bool condition = true;
            string nullMessage = null;

            // Act & Assert
            var exception = Assert.Throws<OutputLengthException>(() => ValidationUtils.CheckOutputLength(condition, nullMessage));
            Assert.That(exception.Message, Is.EqualTo(nullMessage));
        }

        [Test]
        public void CheckOutputLength_WhenConditionIsTrueAndMessageIsEmpty_ThrowsOutputLengthExceptionWithEmptyMessage()
        {
            // Arrange
            bool condition = true;

            // Act & Assert
            var exception = Assert.Throws<OutputLengthException>(() => ValidationUtils.CheckOutputLength(condition, _emptyMessage));
            Assert.That(exception.Message, Is.EqualTo(_emptyMessage));
        }

        [Test]
        public void CheckOutputLength_WhenConditionIsTrueAndMessageIsWhitespace_ThrowsOutputLengthExceptionWithWhitespaceMessage()
        {
            // Arrange
            bool condition = true;

            // Act & Assert
            var exception = Assert.Throws<OutputLengthException>(() => ValidationUtils.CheckOutputLength(condition, _whitespaceMessage));
            Assert.That(exception.Message, Is.EqualTo(_whitespaceMessage));
        }

        [Test]
        public void CheckOutputLength_WhenConditionIsTrueAndMessageIsVeryLong_ThrowsOutputLengthExceptionEfficiently()
        {
            // Arrange
            bool condition = true;
            var stopwatch = System.Diagnostics.Stopwatch.StartNew();

            // Act & Assert
            var exception = Assert.Throws<OutputLengthException>(() => ValidationUtils.CheckOutputLength(condition, _longMessage));
            stopwatch.Stop();
            
            Assert.That(exception.Message, Is.EqualTo(_longMessage));
            Assert.That(stopwatch.ElapsedMilliseconds, Is.LessThan(100)); // TODO: Adjust timeout threshold as needed
        }

        [Test]
        public void CheckOutputLength_WhenConditionIsTrueAndMessageContainsSpecialCharacters_PreservesSpecialCharactersInException()
        {
            // Arrange
            bool condition = true;

            // Act & Assert
            var exception = Assert.Throws<OutputLengthException>(() => ValidationUtils.CheckOutputLength(condition, _specialCharacterMessage));
            Assert.That(exception.Message, Is.EqualTo(_specialCharacterMessage));
        }
    }
}
