// ********RoostGPT********
/*
Test generated by RoostGPT for test csharp-nunit using AI Type AWS Bedrock Runtime AI and AI Model eu.anthropic.claude-sonnet-4-20250514-v1:0

ROOST_METHOD_HASH=Run_e8b1745cfe
ROOST_METHOD_SIG_HASH=Run_404aa09417

   ########## Test - Scenarios ##########  

Scenario 1: Valid Source Vertex with Connected Graph

Details:
  TestName: RunWithValidSourceVertexAndConnectedGraph
  Description: This test verifies that the Bellman-Ford algorithm correctly computes shortest distances from a valid source vertex in a connected directed weighted graph. The test ensures that all reachable vertices have finite distances and unreachable vertices maintain infinite distances.
Execution:
  Arrange: Create a directed weighted graph with multiple vertices and edges, initialize the Bellman-Ford algorithm instance with the graph, and select a valid source vertex that exists in the graph.
  Act: Invoke the Run method with the source vertex as parameter.
  Assert: Use NUnit assertions to verify that the returned dictionary contains all vertices from the graph, the source vertex has distance 0, reachable vertices have finite positive distances, and the distances represent the shortest paths.
Validation:
  The assertion verifies that the algorithm correctly initializes distances and computes shortest paths from the source vertex. This test is crucial for validating the core functionality of the Bellman-Ford algorithm in normal operating conditions.

Scenario 2: Single Vertex Graph

Details:
  TestName: RunWithSingleVertexGraph
  Description: This test checks the algorithm's behavior when the graph contains only one vertex. The source vertex should be the only vertex in the graph, and its distance should be zero.
Execution:
  Arrange: Create a directed weighted graph with a single vertex, initialize the Bellman-Ford algorithm with this graph.
  Act: Call the Run method with the single vertex as the source.
  Assert: Verify that the returned dictionary contains exactly one entry, the single vertex has a distance of 0, and no other vertices are present.
Validation:
  This assertion ensures the algorithm handles the simplest possible graph correctly. It's important for edge case coverage and demonstrates that the algorithm works with minimal input.

Scenario 3: Disconnected Graph with Unreachable Vertices

Details:
  TestName: RunWithDisconnectedGraphHavingUnreachableVertices
  Description: This test validates the algorithm's behavior when the graph contains vertices that are not reachable from the source vertex. Unreachable vertices should maintain infinite distances.
Execution:
  Arrange: Create a directed weighted graph with multiple disconnected components, ensuring some vertices cannot be reached from the chosen source vertex.
  Act: Execute the Run method with a source vertex that cannot reach all other vertices.
  Assert: Confirm that reachable vertices have finite distances, unreachable vertices have infinite distances (double.PositiveInfinity), and the source vertex has distance 0.
Validation:
  This test ensures the algorithm correctly handles disconnected graphs and maintains infinite distances for unreachable vertices, which is the expected behavior in shortest path algorithms.

Scenario 4: Graph with Negative Weight Edges but No Negative Cycles

Details:
  TestName: RunWithNegativeWeightEdgesWithoutNegativeCycles
  Description: This test verifies that the algorithm correctly handles graphs containing negative weight edges while ensuring no negative cycles exist. The algorithm should compute correct shortest distances even with negative weights.
Execution:
  Arrange: Create a directed weighted graph with some negative weight edges but no negative cycles, initialize the algorithm instance.
  Act: Invoke the Run method with a valid source vertex.
  Assert: Verify that the algorithm returns a valid distance dictionary with correct shortest path distances, including negative distances where appropriate.
Validation:
  This assertion validates that the Bellman-Ford algorithm's key advantage over Dijkstra's algorithm - handling negative weights - works correctly when no negative cycles are present.

Scenario 5: Graph with Negative Cycle Detection

Details:
  TestName: RunWithGraphContainingNegativeCycle
  Description: This test ensures that the algorithm properly detects negative cycles in the graph and throws an appropriate exception when such cycles exist.
Execution:
  Arrange: Create a directed weighted graph that contains at least one negative cycle, initialize the Bellman-Ford algorithm with this graph.
  Act: Call the Run method with any valid source vertex.
  Assert: Verify that an appropriate exception is thrown indicating the presence of a negative cycle.
Validation:
  This test is critical for ensuring the algorithm's correctness as negative cycles make shortest path problems undefined. The Bellman-Ford algorithm must detect and report such conditions.

Scenario 6: Null Source Vertex

Details:
  TestName: RunWithNullSourceVertex
  Description: This test validates the algorithm's error handling when a null source vertex is provided as input.
Execution:
  Arrange: Create a valid directed weighted graph and initialize the Bellman-Ford algorithm instance.
  Act: Invoke the Run method with a null source vertex parameter.
  Assert: Verify that an ArgumentNullException is thrown with an appropriate error message.
Validation:
  This assertion ensures proper input validation and prevents the algorithm from attempting to process invalid input, maintaining robust error handling.

Scenario 7: Source Vertex Not in Graph

Details:
  TestName: RunWithSourceVertexNotInGraph
  Description: This test checks the algorithm's behavior when the provided source vertex does not exist in the graph.
Execution:
  Arrange: Create a directed weighted graph with several vertices, create a separate vertex that is not part of the graph, initialize the algorithm.
  Act: Call the Run method with the vertex that doesn't belong to the graph.
  Assert: Verify that an appropriate exception is thrown, such as ArgumentException or KeyNotFoundException.
Validation:
  This test ensures that the algorithm validates input parameters and handles cases where the source vertex is not part of the graph structure.

Scenario 8: Empty Graph

Details:
  TestName: RunWithEmptyGraph
  Description: This test validates the algorithm's behavior when working with an empty graph that contains no vertices.
Execution:
  Arrange: Create an empty directed weighted graph with no vertices, initialize the Bellman-Ford algorithm with this empty graph.
  Act: Attempt to call the Run method with any source vertex (this should fail at the parameter level).
  Assert: Verify that an appropriate exception is thrown indicating that the operation cannot be performed on an empty graph.
Validation:
  This assertion ensures the algorithm gracefully handles edge cases where no vertices exist, preventing potential runtime errors.

Scenario 9: Large Graph Performance Test

Details:
  TestName: RunWithLargeGraphPerformanceValidation
  Description: This test verifies that the algorithm can handle larger graphs efficiently and returns correct results within reasonable time constraints.
Execution:
  Arrange: Create a large directed weighted graph with hundreds of vertices and edges, ensuring no negative cycles exist, initialize the algorithm.
  Act: Execute the Run method with a source vertex and measure execution time.
  Assert: Verify that the algorithm completes within acceptable time limits and returns a valid distance dictionary with correct shortest path calculations.
Validation:
  This test ensures the algorithm's scalability and performance characteristics meet expected standards for practical applications.

Scenario 10: Graph with Self-Loops

Details:
  TestName: RunWithGraphContainingSelfLoops
  Description: This test validates the algorithm's handling of vertices that have edges pointing to themselves (self-loops).
Execution:
  Arrange: Create a directed weighted graph where some vertices have self-loops with various weights (positive, negative, zero), initialize the algorithm.
  Act: Call the Run method with a source vertex that has or can reach vertices with self-loops.
  Assert: Verify that self-loops are handled correctly and don't interfere with shortest path calculations to other vertices.
Validation:
  This assertion ensures the algorithm properly processes self-loops and maintains correct shortest path calculations in their presence.

Scenario 11: Zero Weight Edges

Details:
  TestName: RunWithZeroWeightEdges
  Description: This test checks the algorithm's behavior when the graph contains edges with zero weight.
Execution:
  Arrange: Create a directed weighted graph with some edges having zero weight, initialize the Bellman-Ford algorithm.
  Act: Invoke the Run method with a valid source vertex.
  Assert: Verify that zero-weight edges are processed correctly and contribute appropriately to shortest path calculations.
Validation:
  This test ensures that zero-weight edges don't cause any computational issues and are handled as valid path components in distance calculations.

Scenario 12: Multiple Paths with Same Distance

Details:
  TestName: RunWithMultiplePathsSameDistance
  Description: This test validates the algorithm's behavior when multiple paths exist between vertices with identical total distances.
Execution:
  Arrange: Create a directed weighted graph where multiple different paths between the same pair of vertices have identical total weights.
  Act: Execute the Run method with an appropriate source vertex.
  Assert: Verify that the algorithm returns the correct shortest distance regardless of which specific path is chosen.
Validation:
  This assertion ensures the algorithm correctly identifies shortest distances even when multiple optimal paths exist, demonstrating correctness in ambiguous scenarios.


================================VULNERABILITIES================================
Vulnerability: CWE-476: NULL Pointer Dereference
Issue: The InitializeDistances method accepts sourceVertex parameter without null validation. If a null sourceVertex is passed, distances[sourceVertex] = 0 will throw NullReferenceException when used as dictionary key.
Solution: Add null validation at the beginning of InitializeDistances method: if (sourceVertex == null) throw new ArgumentNullException(nameof(sourceVertex));

Vulnerability: CWE-674: Uncontrolled Recursion
Issue: RelaxEdges method has nested loops iterating over graph.Vertices with O(V²) complexity without bounds checking. Large graphs could cause stack overflow or excessive CPU consumption leading to DoS.
Solution: Implement vertex count validation and timeout mechanisms: Add maximum vertex limit check and consider using CancellationToken for long-running operations.

Vulnerability: CWE-362: Concurrent Execution using Shared Resource with Improper Synchronization
Issue: The distances and predecessors dictionaries are shared state accessed across multiple methods without thread synchronization. Concurrent access could lead to race conditions and data corruption.
Solution: Use ConcurrentDictionary<Vertex<T>, double> for distances and predecessors, or implement proper locking mechanisms using lock statements around dictionary operations.

Vulnerability: CWE-400: Uncontrolled Resource Consumption
Issue: The Run method returns the entire distances dictionary without defensive copying. Caller can modify returned dictionary affecting internal state and potentially causing memory leaks or state corruption.
Solution: Return a defensive copy of distances dictionary: return new Dictionary<Vertex<T>, double>(distances); or use IReadOnlyDictionary<Vertex<T>, double> as return type.

Vulnerability: CWE-248: Uncaught Exception
Issue: CheckForNegativeCycles and RelaxEdgesForVertex methods are called without exception handling. Exceptions in these dependency methods could crash the application without proper error recovery.
Solution: Wrap method calls in try-catch blocks and implement proper exception handling: try { CheckForNegativeCyclesForVertex(vertex); } catch (Exception ex) { /* Log and handle appropriately */ }

================================================================================

*/

// ********RoostGPT********
using System;
using System.Collections.Generic;
using NUnit.Framework;
using DataStructures.Graph;
using Algorithms.Graph;

namespace Algorithms.Graph.Test
{
    [TestFixture]
    public class RunTest
    {
        private DirectedWeightedGraph<int> graph;
        private BellmanFord<int> bellmanFord;

        [SetUp]
        public void SetUp()
        {
            // Initialize common test variables
            graph = new DirectedWeightedGraph<int>();
        }

        [Test]
        public void RunWithValidSourceVertexAndConnectedGraph()
        {
            // Arrange
            var vertex1 = new Vertex<int>(1);
            var vertex2 = new Vertex<int>(2);
            var vertex3 = new Vertex<int>(3);
            var vertex4 = new Vertex<int>(4);

            graph.AddVertex(vertex1);
            graph.AddVertex(vertex2);
            graph.AddVertex(vertex3);
            graph.AddVertex(vertex4);

            graph.AddEdge(vertex1, vertex2, 4);
            graph.AddEdge(vertex1, vertex3, 2);
            graph.AddEdge(vertex2, vertex4, 3);
            graph.AddEdge(vertex3, vertex4, 1);

            bellmanFord = new BellmanFord<int>(graph);

            // Act
            var result = bellmanFord.Run(vertex1);

            // Assert
            Assert.That(result.Count, Is.EqualTo(4));
            Assert.That(result[vertex1], Is.EqualTo(0));
            Assert.That(result[vertex2], Is.EqualTo(4));
            Assert.That(result[vertex3], Is.EqualTo(2));
            Assert.That(result[vertex4], Is.EqualTo(3));
        }

        [Test]
        public void RunWithSingleVertexGraph()
        {
            // Arrange
            var singleVertex = new Vertex<int>(1);
            graph.AddVertex(singleVertex);
            bellmanFord = new BellmanFord<int>(graph);

            // Act
            var result = bellmanFord.Run(singleVertex);

            // Assert
            Assert.That(result.Count, Is.EqualTo(1));
            Assert.That(result[singleVertex], Is.EqualTo(0));
        }

        [Test]
        public void RunWithDisconnectedGraphHavingUnreachableVertices()
        {
            // Arrange
            var vertex1 = new Vertex<int>(1);
            var vertex2 = new Vertex<int>(2);
            var vertex3 = new Vertex<int>(3);
            var vertex4 = new Vertex<int>(4);

            graph.AddVertex(vertex1);
            graph.AddVertex(vertex2);
            graph.AddVertex(vertex3);
            graph.AddVertex(vertex4);

            graph.AddEdge(vertex1, vertex2, 1);
            // vertex3 and vertex4 are disconnected from vertex1

            bellmanFord = new BellmanFord<int>(graph);

            // Act
            var result = bellmanFord.Run(vertex1);

            // Assert
            Assert.That(result[vertex1], Is.EqualTo(0));
            Assert.That(result[vertex2], Is.EqualTo(1));
            Assert.That(result[vertex3], Is.EqualTo(double.PositiveInfinity));
            Assert.That(result[vertex4], Is.EqualTo(double.PositiveInfinity));
        }

        [Test]
        public void RunWithNegativeWeightEdgesWithoutNegativeCycles()
        {
            // Arrange
            var vertex1 = new Vertex<int>(1);
            var vertex2 = new Vertex<int>(2);
            var vertex3 = new Vertex<int>(3);

            graph.AddVertex(vertex1);
            graph.AddVertex(vertex2);
            graph.AddVertex(vertex3);

            graph.AddEdge(vertex1, vertex2, -1);
            graph.AddEdge(vertex2, vertex3, 2);
            graph.AddEdge(vertex1, vertex3, 4);

            bellmanFord = new BellmanFord<int>(graph);

            // Act
            var result = bellmanFord.Run(vertex1);

            // Assert
            Assert.That(result[vertex1], Is.EqualTo(0));
            Assert.That(result[vertex2], Is.EqualTo(-1));
            Assert.That(result[vertex3], Is.EqualTo(1));
        }

        [Test]
        public void RunWithGraphContainingNegativeCycle()
        {
            // Arrange
            var vertex1 = new Vertex<int>(1);
            var vertex2 = new Vertex<int>(2);
            var vertex3 = new Vertex<int>(3);

            graph.AddVertex(vertex1);
            graph.AddVertex(vertex2);
            graph.AddVertex(vertex3);

            graph.AddEdge(vertex1, vertex2, 1);
            graph.AddEdge(vertex2, vertex3, -3);
            graph.AddEdge(vertex3, vertex1, 1); // Creates negative cycle

            bellmanFord = new BellmanFord<int>(graph);

            // Act & Assert
            Assert.Throws<InvalidOperationException>(() => bellmanFord.Run(vertex1));
        }

        [Test]
        public void RunWithNullSourceVertex()
        {
            // Arrange
            var vertex1 = new Vertex<int>(1);
            graph.AddVertex(vertex1);
            bellmanFord = new BellmanFord<int>(graph);

            // Act & Assert
            Assert.Throws<ArgumentNullException>(() => bellmanFord.Run(null));
        }

        [Test]
        public void RunWithSourceVertexNotInGraph()
        {
            // Arrange
            var vertex1 = new Vertex<int>(1);
            var vertex2 = new Vertex<int>(2);
            var vertexNotInGraph = new Vertex<int>(99);

            graph.AddVertex(vertex1);
            graph.AddVertex(vertex2);
            bellmanFord = new BellmanFord<int>(graph);

            // Act & Assert
            Assert.Throws<ArgumentException>(() => bellmanFord.Run(vertexNotInGraph));
        }

        [Test]
        public void RunWithEmptyGraph()
        {
            // Arrange
            var emptyGraph = new DirectedWeightedGraph<int>();
            var someVertex = new Vertex<int>(1);
            bellmanFord = new BellmanFord<int>(emptyGraph);

            // Act & Assert
            Assert.Throws<ArgumentException>(() => bellmanFord.Run(someVertex));
        }

        [Test]
        public void RunWithLargeGraphPerformanceValidation()
        {
            // Arrange
            var vertices = new List<Vertex<int>>();
            for (int i = 0; i < 100; i++) // TODO: Adjust size based on performance requirements
            {
                var vertex = new Vertex<int>(i);
                vertices.Add(vertex);
                graph.AddVertex(vertex);
            }

            // Create edges to form a connected graph
            for (int i = 0; i < vertices.Count - 1; i++)
            {
                graph.AddEdge(vertices[i], vertices[i + 1], i + 1);
            }

            bellmanFord = new BellmanFord<int>(graph);
            var stopwatch = System.Diagnostics.Stopwatch.StartNew();

            // Act
            var result = bellmanFord.Run(vertices[0]);

            // Assert
            stopwatch.Stop();
            Assert.That(stopwatch.ElapsedMilliseconds, Is.LessThan(5000)); // TODO: Adjust timeout as needed
            Assert.That(result.Count, Is.EqualTo(100));
            Assert.That(result[vertices[0]], Is.EqualTo(0));
        }

        [Test]
        public void RunWithGraphContainingSelfLoops()
        {
            // Arrange
            var vertex1 = new Vertex<int>(1);
            var vertex2 = new Vertex<int>(2);

            graph.AddVertex(vertex1);
            graph.AddVertex(vertex2);

            graph.AddEdge(vertex1, vertex1, 2); // Self-loop with positive weight
            graph.AddEdge(vertex1, vertex2, 3);
            graph.AddEdge(vertex2, vertex2, 0); // Self-loop with zero weight

            bellmanFord = new BellmanFord<int>(graph);

            // Act
            var result = bellmanFord.Run(vertex1);

            // Assert
            Assert.That(result[vertex1], Is.EqualTo(0));
            Assert.That(result[vertex2], Is.EqualTo(3));
        }

        [Test]
        public void RunWithZeroWeightEdges()
        {
            // Arrange
            var vertex1 = new Vertex<int>(1);
            var vertex2 = new Vertex<int>(2);
            var vertex3 = new Vertex<int>(3);

            graph.AddVertex(vertex1);
            graph.AddVertex(vertex2);
            graph.AddVertex(vertex3);

            graph.AddEdge(vertex1, vertex2, 0);
            graph.AddEdge(vertex2, vertex3, 5);
            graph.AddEdge(vertex1, vertex3, 10);

            bellmanFord = new BellmanFord<int>(graph);

            // Act
            var result = bellmanFord.Run(vertex1);

            // Assert
            Assert.That(result[vertex1], Is.EqualTo(0));
            Assert.That(result[vertex2], Is.EqualTo(0));
            Assert.That(result[vertex3], Is.EqualTo(5));
        }

        [Test]
        public void RunWithMultiplePathsSameDistance()
        {
            // Arrange
            var vertex1 = new Vertex<int>(1);
            var vertex2 = new Vertex<int>(2);
            var vertex3 = new Vertex<int>(3);
            var vertex4 = new Vertex<int>(4);

            graph.AddVertex(vertex1);
            graph.AddVertex(vertex2);
            graph.AddVertex(vertex3);
            graph.AddVertex(vertex4);

            // Two paths from vertex1 to vertex4 with same total distance
            graph.AddEdge(vertex1, vertex2, 2);
            graph.AddEdge(vertex2, vertex4, 3);
            graph.AddEdge(vertex1, vertex3, 1);
            graph.AddEdge(vertex3, vertex4, 4);

            bellmanFord = new BellmanFord<int>(graph);

            // Act
            var result = bellmanFord.Run(vertex1);

            // Assert
            Assert.That(result[vertex1], Is.EqualTo(0));
            Assert.That(result[vertex4], Is.EqualTo(5)); // Both paths have distance 5
        }
    }
}
